# Configuration File
#

title: Tutorials
author: CCATS Group
copyright: "2023"
logo: "assets/img/schrodinger_cat2_black.png"

html:
  baseurl: https//cc-ats.github.io/Tutorials
  use_repository_button: true
  use_multitoc_numbering: True

html_theme_options:
  logo:
    text: "CCATS Group"
    image_dark: "assets/img/schrodinger_cat2_white.png"

exclude_patterns: [
  'assets/',
  'assets/*',
  '.ipynb_checkpoints', 
  '*/.ipynb_checkpoints', 
  '.DS_STORE', 
  'build.sh']

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  run_in_temp: true
  timeout: 300
  exclude_patterns:
    - 'ColabFold/AlphaFold2.ipynb'
    - 'ColabFold/Tutorial-Monomer.ipynb'
    - 'ColabFold/Tutorial-Multimer.ipynb'

parse:
  myst_enable_extensions:  
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/cc-ats/Tutorials  # Online location of your book
  path_to_book: ./  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
launch_buttons:
  colab_url: "https://colab.research.google.com"
html:
  use_issues_button: true
  use_repository_button: true
